In [3]:
import numpy as np
import random
from numba import njit
import pandas as pd
import constants
from constants import UP, DOWN, LEFT, RIGHT
from typing import List, Union, Tuple
from staticboard import NumpyStaticBoard

pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [4]:
matrix = np.array([
            [0, 0, 2, 2],
            [0, 0, 0, 0],
            [0, 2, 4, 0],
            [2, 0, 0, 2]
        ]).astype('int8')

In [14]:
random.seed(0)
np.random.seed(0)
empty_cell_coordinates = np.argwhere(matrix == 0)
None if len(empty_cell_coordinates) == 0 else empty_cell_coordinates[
    random.randint(0, len(empty_cell_coordinates) - 1)]
# NumpyStaticBoard.get_random_empty_cell_coordinate(matrix)

array([2, 0])

In [15]:
NumpyStaticBoard.get_random_empty_cell_coordinate(matrix)

array([1, 1])

In [9]:
def move(matrix: np.ndarray, direction: Union[UP, DOWN, LEFT, RIGHT], inplace: bool = True) -> Tuple[np.ndarray, bool]:
    score = 0
    changed = False
    if not inplace:
        matrix = matrix.clone()
    for i in range(len(matrix)):
        if direction == UP:
            arr, score_, changed_ = NumpyStaticBoard.collapse_array(
                matrix[:, i], reverse=True)
        elif direction == DOWN:
            arr, score_, changed_ = NumpyStaticBoard.collapse_array(
                matrix[:, i], reverse=False)
        elif direction == LEFT:
            arr, score_, changed_ = NumpyStaticBoard.collapse_array(
                matrix[i, :], reverse=True)
        elif direction == RIGHT:
            arr, score_, changed_ = NumpyStaticBoard.collapse_array(
                matrix[i, :], reverse=False)
        else:
            raise ValueError(f"Invalid direction: {direction}")
        changed = max(changed, changed_)
        score += score_
    return matrix, score, changed

In [17]:
%%time
move(matrix, RIGHT)

CPU times: user 171 ms, sys: 0 ns, total: 171 ms
Wall time: 170 ms


(array([[0, 0, 0, 4],
        [0, 0, 0, 0],
        [0, 0, 2, 4],
        [0, 0, 0, 4]], dtype=int8),
 8,
 True)

In [15]:
matrix.clone()

AttributeError: 'numpy.ndarray' object has no attribute 'clone'

In [126]:
%%time
collapse_array(np.array([0, 2, 2, 0]))

CPU times: user 17 µs, sys: 0 ns, total: 17 µs
Wall time: 19.1 µs


(array([0, 0, 0, 4]), 4, True)

In [83]:
np.array([0, 2, 2, 0]) == np.array([0, 0, 0, 4])

array([ True, False, False, False])

In [78]:
np.arange(1, 17).reshape(4, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [10]:
%time get_neighbors_coordinates(matrix, 0, 0)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Type of variable 'result' cannot be determined, operation: $8call_method.3, location: <ipython-input-9-edf98b61dbce> (3)

File "<ipython-input-9-edf98b61dbce>", line 3:
def get_neighbors_coordinates(matrix: np.ndarray, row_i: int, col_i: int) -> np.ndarray:
    result = np.array([])
    ^


In [6]:
%time NumpyStaticBoard.get_neighbors_coordinates(matrix, 0, 0)

CPU times: user 11 µs, sys: 0 ns, total: 11 µs
Wall time: 12.2 µs


array([[1, 0],
       [0, 1]])