In [41]:
import game
import torch
import constants
import numpy as np
from game import TorchStaticBoard
from torch import Tensor

In [95]:
matrix = torch.Tensor([
    [0, 0, 0, 2],
    [2, 0, 0, 2],
    [0, 0, 0, 0],
    [0, 0, 0, 0]
])

In [96]:
%%time
g = game.Game(matrix=matrix)

init random seed to 2048
CPU times: user 594 µs, sys: 96 µs, total: 690 µs
Wall time: 617 µs


In [99]:
%%time
g.move(constants.RIGHT, inplace=False)

CPU times: user 2.69 ms, sys: 0 ns, total: 2.69 ms
Wall time: 2.08 ms


(tensor([[0., 0., 0., 2.],
         [2., 0., 0., 2.],
         [0., 0., 0., 0.],
         [0., 2., 0., 0.]]),
 4,
 True)

In [92]:
%%time
TorchStaticBoard.move(matrix=matrix, direction=constants.RIGHT, inplace=True)

CPU times: user 1.79 ms, sys: 287 µs, total: 2.08 ms
Wall time: 1.55 ms


(tensor([[0., 0., 0., 4.],
         [0., 0., 0., 8.],
         [0., 0., 0., 2.],
         [0., 0., 0., 2.]]),
 0,
 False)

In [114]:
%%time
TorchStaticBoard.get_random_empty_cell_coordinate(matrix)

CPU times: user 612 µs, sys: 0 ns, total: 612 µs
Wall time: 299 µs


tensor([2, 0])

In [115]:
%%time
TorchStaticBoard.get_empty_coordinates(matrix)

CPU times: user 599 µs, sys: 96 µs, total: 695 µs
Wall time: 341 µs


tensor([[0, 0],
        [0, 1],
        [0, 2],
        [1, 1],
        [1, 2],
        [2, 0],
        [2, 1],
        [2, 2],
        [2, 3],
        [3, 0],
        [3, 1],
        [3, 2],
        [3, 3]])

In [88]:
%%time
TorchStaticBoard.set_random_cell(matrix, inplace=True)

CPU times: user 571 µs, sys: 58 µs, total: 629 µs
Wall time: 446 µs


(tensor([[0., 2., 0., 2.],
         [2., 2., 2., 2.],
         [0., 0., 0., 2.],
         [0., 0., 0., 2.]]),
 True)

In [101]:
%%time
TorchStaticBoard.collapse_array(torch.tensor([0, 2, 0, 2]))

CPU times: user 1.61 ms, sys: 0 ns, total: 1.61 ms
Wall time: 1.15 ms


(tensor([0, 0, 0, 4]), 4, True)

In [79]:
matrix

tensor([[0., 0., 0., 2.],
        [2., 2., 0., 2.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [83]:
%%time
TorchStaticBoard.compute_is_done(matrix)

CPU times: user 702 µs, sys: 113 µs, total: 815 µs
Wall time: 484 µs


False

In [48]:
%%time
game.TorchStaticBoard.get_empty_matrix()

CPU times: user 817 µs, sys: 0 ns, total: 817 µs
Wall time: 413 µs


tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [102]:
def collapse_arr(arr: Tensor, reverse=False):
    """
    collapse an array in left-to-right direction in 2048-way inplace, this is either a row or an column
    :param array: Tensor Array
    :return:
    """
    arr_len = len(arr)
    changed = False
    score = 0
    has_merged_arr = torch.zeros_like(arr)
    for i in range(arr_len - 2, -1, -1):
        curr_i = i
        for next_i in range(i + 1, arr_len, 1):
            if arr[next_i] == 0 and arr[curr_i] != 0:
                arr[next_i] = arr[curr_i]
                arr[curr_i] = 0
                curr_i = next_i
                changed = True
            elif arr[curr_i] == arr[next_i] and not has_merged_arr[next_i] and arr[curr_i] != 0:
                # merge case
                arr[next_i] *= 2
                arr[curr_i] = 0
                has_merged_arr[next_i] = 1
                score += int(arr[next_i])
                changed = True
                break
            else:
                break
    return arr, score, changed

In [107]:
arr = Tensor([0, 2, 0, 2])

In [111]:
%%time
collapse_arr(arr)

CPU times: user 1.41 ms, sys: 22 µs, total: 1.43 ms
Wall time: 802 µs


(tensor([0., 0., 0., 4.]), 0, False)

In [105]:
def collapse_array(arr: Tensor, reverse=False):
    """
    collapse an array in left-to-right direction in 2048-way inplace, this is either a row or an column
    :param array: Tensor Array
    :return:
    """
    arr_len = len(arr)
    changed = False
    score = 0
    has_merged_arr = torch.zeros_like(arr)
    for i in range(1 if reverse else arr_len - 2, arr_len if reverse else -1, 1 if reverse else -1):
        curr_i = i
        for next_i in range(i + (-1 if reverse else 1), -1 if reverse else arr_len, -1 if reverse else 1):
            if arr[next_i] == 0 and arr[curr_i] != 0:
                arr[next_i] = arr[curr_i]
                arr[curr_i] = 0
                curr_i = next_i
                changed = True
            elif arr[curr_i] == arr[next_i] and not has_merged_arr[next_i] and arr[curr_i] != 0:
                # merge case
                arr[next_i] *= 2
                arr[curr_i] = 0
                has_merged_arr[next_i] = 1
                score += int(arr[next_i])
                changed = True
                break
            else:
                break
    return arr, score, changed


In [113]:
%%time
collapse_arr(arr)

CPU times: user 1.5 ms, sys: 241 µs, total: 1.75 ms
Wall time: 944 µs


(tensor([0., 0., 0., 4.]), 0, False)

In [ ]:
%%time


In [54]:
%%time
matrix

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 8.34 µs


tensor([[0., 0., 0., 2.],
        [2., 0., 0., 2.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [124]:
def get_empty_coordinates(matrix: Tensor) -> Tensor:
    return torch.nonzero(matrix == 0)

def get_empty_coordinates_loop(matrix: Tensor):
    result = []
    h, w = matrix.shape
    for row_index in range(h):
        for col_index in range(w):
            if matrix[row_index, col_index] == 0:
                result.append((row_index, col_index))
    return result

In [131]:
%%time
get_empty_coordinates_loop(matrix)

CPU times: user 1.66 ms, sys: 0 ns, total: 1.66 ms
Wall time: 956 µs


In [127]:
%%time
get_empty_coordinates(matrix)

CPU times: user 249 µs, sys: 40 µs, total: 289 µs
Wall time: 190 µs


tensor([[0, 0],
        [0, 1],
        [0, 2],
        [1, 1],
        [1, 2],
        [2, 0],
        [2, 1],
        [2, 2],
        [2, 3],
        [3, 0],
        [3, 1],
        [3, 2],
        [3, 3]])

In [32]:
%%time
for i in range(50):
    x = np.zeros((10000, 10000))

CPU times: user 0 ns, sys: 1.25 ms, total: 1.25 ms
Wall time: 879 µs


In [ ]:
%%time


In [ ]:
%%time
