In [152]:
import game
import torch
import constants
import gamestate
import components
import numpy as np
from torch import Tensor
from numba import jit, njit

In [3]:
matrix = [
    [None, None, None, 2],
    [2, None, None, 2],
    [None, None, None, None],
    [None, None, None, None]
]

In [4]:
%%time
game_ = gamestate.GameState(matrix=matrix)

CPU times: user 97 µs, sys: 8 µs, total: 105 µs
Wall time: 108 µs


In [6]:
%%time
game_.move(constants.RIGHT)

CPU times: user 137 µs, sys: 0 ns, total: 137 µs
Wall time: 141 µs


(4, True)

In [27]:
%%time
game_._board.get_empty_tiles_pos()

CPU times: user 20 µs, sys: 2 µs, total: 22 µs
Wall time: 25.5 µs


[(0, 1), (0, 2), (1, 0), (1, 1), (2, 1), (3, 0), (3, 1), (3, 2), (3, 3)]

In [8]:
%%time
game_.compute_is_done()

CPU times: user 27 µs, sys: 2 µs, total: 29 µs
Wall time: 31.7 µs


False

In [12]:
%%time
game_.set_random_tile()

CPU times: user 38 µs, sys: 0 ns, total: 38 µs
Wall time: 39.1 µs


In [202]:
def get_empty_coordinates(matrix):
    # return torch.nonzero(matrix == 0)
    return np.argwhere(matrix==0)

@njit
def get_empty_coordinates_nb(matrix):
    # return torch.nonzero(matrix == 0)
    return np.argwhere(matrix==0)

def get_empty_coordinates_loop(matrix):
    result = []
    h, w = len(matrix), len(matrix[0])
    # h, w = matrix.shape
    for row_index in range(h):
        for col_index in range(w):
            if matrix[row_index][col_index] == 0:
                result.append((row_index, col_index))
    return result

@njit
def get_empty_coordinates_loop_nb(matrix):
    result = []
    h, w = len(matrix), len(matrix[0])
    # h, w = matrix.shape
    for row_index in range(h):
        for col_index in range(w):
            if matrix[row_index][col_index] == 0:
                result.append((row_index, col_index))
    return result

In [231]:
matrix = np.array([
    [0, 0, 0, 2],
    [2, 0, 0, 2],
    [0, 0, 0, 0],
    [0, 0, 0, 0]
])
# matrix = [
#     [0, 0, 0, 2],
#     [2, 0, 0, 2],
#     [0, 0, 0, 0],
#     [0, 0, 0, 0]
# ]

# matrix = Tensor([
#     [0, 0, 0, 2],
#     [2, 0, 0, 2],
#     [0, 0, 0, 0],
#     [0, 0, 0, 0]
# ])

matrix = np.random.rand(100, 100)
matrix = np.where(matrix > 0.5, 1, 0)

In [234]:
%%time
get_empty_coordinates_loop(matrix)

CPU times: user 4.68 ms, sys: 0 ns, total: 4.68 ms
Wall time: 4.66 ms


[(0, 0),
 (0, 3),
 (0, 5),
 (0, 6),
 (0, 7),
 (0, 10),
 (0, 11),
 (0, 12),
 (0, 14),
 (0, 16),
 (0, 17),
 (0, 19),
 (0, 22),
 (0, 26),
 (0, 31),
 (0, 33),
 (0, 35),
 (0, 37),
 (0, 41),
 (0, 45),
 (0, 48),
 (0, 51),
 (0, 56),
 (0, 57),
 (0, 60),
 (0, 61),
 (0, 62),
 (0, 67),
 (0, 71),
 (0, 72),
 (0, 73),
 (0, 76),
 (0, 78),
 (0, 82),
 (0, 83),
 (0, 86),
 (0, 88),
 (0, 89),
 (0, 92),
 (0, 95),
 (0, 96),
 (0, 97),
 (1, 0),
 (1, 1),
 (1, 2),
 (1, 4),
 (1, 7),
 (1, 9),
 (1, 11),
 (1, 12),
 (1, 13),
 (1, 14),
 (1, 17),
 (1, 18),
 (1, 19),
 (1, 22),
 (1, 27),
 (1, 29),
 (1, 31),
 (1, 32),
 (1, 37),
 (1, 42),
 (1, 43),
 (1, 45),
 (1, 47),
 (1, 49),
 (1, 50),
 (1, 51),
 (1, 52),
 (1, 54),
 (1, 55),
 (1, 57),
 (1, 58),
 (1, 60),
 (1, 61),
 (1, 63),
 (1, 67),
 (1, 68),
 (1, 71),
 (1, 73),
 (1, 74),
 (1, 75),
 (1, 76),
 (1, 77),
 (1, 79),
 (1, 81),
 (1, 82),
 (1, 85),
 (1, 86),
 (1, 89),
 (1, 90),
 (1, 91),
 (1, 93),
 (1, 95),
 (1, 97),
 (1, 98),
 (1, 99),
 (2, 2),
 (2, 3),
 (2, 5),
 (2, 7),
 (2, 

In [245]:
%%time
get_empty_coordinates_loop_nb(matrix)

CPU times: user 443 µs, sys: 16 µs, total: 459 µs
Wall time: 464 µs


[(0, 0),
 (0, 3),
 (0, 5),
 (0, 6),
 (0, 7),
 (0, 10),
 (0, 11),
 (0, 12),
 (0, 14),
 (0, 16),
 (0, 17),
 (0, 19),
 (0, 22),
 (0, 26),
 (0, 31),
 (0, 33),
 (0, 35),
 (0, 37),
 (0, 41),
 (0, 45),
 (0, 48),
 (0, 51),
 (0, 56),
 (0, 57),
 (0, 60),
 (0, 61),
 (0, 62),
 (0, 67),
 (0, 71),
 (0, 72),
 (0, 73),
 (0, 76),
 (0, 78),
 (0, 82),
 (0, 83),
 (0, 86),
 (0, 88),
 (0, 89),
 (0, 92),
 (0, 95),
 (0, 96),
 (0, 97),
 (1, 0),
 (1, 1),
 (1, 2),
 (1, 4),
 (1, 7),
 (1, 9),
 (1, 11),
 (1, 12),
 (1, 13),
 (1, 14),
 (1, 17),
 (1, 18),
 (1, 19),
 (1, 22),
 (1, 27),
 (1, 29),
 (1, 31),
 (1, 32),
 (1, 37),
 (1, 42),
 (1, 43),
 (1, 45),
 (1, 47),
 (1, 49),
 (1, 50),
 (1, 51),
 (1, 52),
 (1, 54),
 (1, 55),
 (1, 57),
 (1, 58),
 (1, 60),
 (1, 61),
 (1, 63),
 (1, 67),
 (1, 68),
 (1, 71),
 (1, 73),
 (1, 74),
 (1, 75),
 (1, 76),
 (1, 77),
 (1, 79),
 (1, 81),
 (1, 82),
 (1, 85),
 (1, 86),
 (1, 89),
 (1, 90),
 (1, 91),
 (1, 93),
 (1, 95),
 (1, 97),
 (1, 98),
 (1, 99),
 (2, 2),
 (2, 3),
 (2, 5),
 (2, 7),
 (2, 

In [241]:
%%time
get_empty_coordinates(matrix)

CPU times: user 836 µs, sys: 0 ns, total: 836 µs
Wall time: 510 µs


array([[ 0,  0],
       [ 0,  3],
       [ 0,  5],
       ...,
       [99, 94],
       [99, 98],
       [99, 99]])

In [238]:
%%time
get_empty_coordinates_nb(matrix)

CPU times: user 60 µs, sys: 2 µs, total: 62 µs
Wall time: 64.6 µs


array([[ 0,  0],
       [ 0,  3],
       [ 0,  5],
       ...,
       [99, 94],
       [99, 98],
       [99, 99]])

In [177]:
%%time
get_empty_coordinates_loop(matrix.numpy())

CPU times: user 70 µs, sys: 0 ns, total: 70 µs
Wall time: 72.7 µs


[(0, 0),
 (0, 1),
 (0, 2),
 (1, 1),
 (1, 2),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3),
 (3, 0),
 (3, 1),
 (3, 2),
 (3, 3)]

In [199]:
%%time
get_empty_coordinates_nb(matrix.numpy())

CPU times: user 23 µs, sys: 1e+03 ns, total: 24 µs
Wall time: 26 µs


array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 1],
       [1, 2],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [3, 0],
       [3, 1],
       [3, 2],
       [3, 3]])

In [187]:
%%time
get_empty_coordinates_loop_nb(matrix.numpy())

CPU times: user 20 µs, sys: 0 ns, total: 20 µs
Wall time: 22.2 µs


[(0, 0),
 (0, 1),
 (0, 2),
 (1, 1),
 (1, 2),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3),
 (3, 0),
 (3, 1),
 (3, 2),
 (3, 3)]

In [201]:
%%time
get_empty_coordinates_loop_nb(matrix.tolist())

TypeError: Failed in nopython mode pipeline (step: nopython mode backend)
cannot reflect element of reflected container: reflected list(reflected list(float64)<iv=None>)<iv=None>


In [150]:
%%time
get_empty_coordinates_loop(matrix.tolist())

CPU times: user 19 µs, sys: 0 ns, total: 19 µs
Wall time: 21.7 µs


[(0, 0),
 (0, 1),
 (0, 2),
 (1, 1),
 (1, 2),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3),
 (3, 0),
 (3, 1),
 (3, 2),
 (3, 3)]

In [38]:
%%time
get_empty_coordinates(matrix)

CPU times: user 43 µs, sys: 4 µs, total: 47 µs
Wall time: 48.2 µs


array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 1],
       [1, 2],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [3, 0],
       [3, 1],
       [3, 2],
       [3, 3]])

In [34]:
%%time
np.argwhere(matrix==0)

CPU times: user 93 µs, sys: 0 ns, total: 93 µs
Wall time: 87.3 µs


array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 1],
       [1, 2],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [3, 0],
       [3, 1],
       [3, 2],
       [3, 3]])

In [ ]:
%%time


In [ ]:
%%time


In [ ]:
%%time


In [131]:
matrix = (torch.rand((4, 4))*10).int().detach()
np_matrix = matrix.numpy()
l_matrix = matrix.tolist()

In [82]:
%%time
t_lg_lst = torch.rand((100, 100, 100))

CPU times: user 6.3 ms, sys: 0 ns, total: 6.3 ms
Wall time: 5.74 ms


In [81]:
%%time
np_lg_lst = t_lg_lst.numpy()

CPU times: user 15 µs, sys: 0 ns, total: 15 µs
Wall time: 16.7 µs


In [93]:
%%time
list_lg_lst = t_lg_lst.tolist()

CPU times: user 23 ms, sys: 12.3 ms, total: 35.4 ms
Wall time: 37 ms


In [118]:
def flatten(m):
    lst = []
    for i in range(len(m)):
        for j in range(len(m[i])):
            lst.append(m[i][j])
    return lst

In [136]:
%%time
x = flatten(matrix)

CPU times: user 90 µs, sys: 0 ns, total: 90 µs
Wall time: 92.3 µs


In [139]:
%%time
x = flatten(matrix.numpy())

CPU times: user 24 µs, sys: 1e+03 ns, total: 25 µs
Wall time: 25.7 µs


In [145]:
%%time
x = flatten(matrix.tolist())

CPU times: user 20 µs, sys: 0 ns, total: 20 µs
Wall time: 22.9 µs


In [ ]:
%%time
x = flatten(matrix)

In [105]:
%%time
x = flatten(np_lg_lst)

CPU times: user 362 ms, sys: 3.91 ms, total: 366 ms
Wall time: 365 ms


In [117]:
%%time
x = flatten(t_lg_lst.tolist())

CPU times: user 119 ms, sys: 8.08 ms, total: 127 ms
Wall time: 126 ms
